// <auto-generated>
// Written by tools/builtin_checksums.py from the whisper-v1.9.4-1 release. Don't edit by hand.
// </auto-generated>

using System.Collections.Generic;

namespace Jellyfin.Plugin.Subtitles.SpeechToText.BuiltIn;

internal static partial class BuiltInRelease
{
    internal const string Tag = "whisper-v1.9.4-1";

    private static IReadOnlyList<BuiltInDownload> Downloads { get; } =
    [
        new("ggml-base-q8_0.bin", "c577b9a86e7e048a0b7eada054f4dd79a56bbfa911fbdacf900ac5b567cbb7d9", 81768585, null),
        new("ggml-small-q5_1.bin", "ae85e4a935d7a567bd102fe55afc16bb595bdb618e11b2fc7591bc08120411bb", 190085487, null),
        new("whisper-cli-linux-arm64.zip", "84bf96340165c06e52e05bc9a07ba73dfe177d37d3a46b347f1be483a259dea7", 7070095, new Dictionary<string, string>
        {
            ["LICENSE-whisper.cpp.txt"] = "94f29bbed6a22c35b992c5c6ebf0e7c92f13b836b90f36f461c9cf2f0f1d010d",
            ["libggml-base.so"] = "d1750fc816f03a01b13999550bf91850992d23633c564bedaef0e20d93aa6379",
            ["libggml-base.so.0"] = "d1750fc816f03a01b13999550bf91850992d23633c564bedaef0e20d93aa6379",
            ["libggml-base.so.0.23.0"] = "d1750fc816f03a01b13999550bf91850992d23633c564bedaef0e20d93aa6379",
            ["libggml-cpu-armv8.0_1.so"] = "2428be8ff27fd68bf11455eb53479166aa90d03062402a6644584ff338ec2b96",
            ["libggml-cpu-armv8.2_1.so"] = "a714211fd21f776225fbba04a7e8909ad5e568eeab4d11c4340d053c814b0f09",
            ["libggml-cpu-armv8.2_2.so"] = "a247c42d0ce7239008c753eaa8a21fc6341ba340c97f950f47a702ffcc507de7",
            ["libggml-cpu-armv8.2_3.so"] = "232550a4bc81a3296241bebb712c411e287026b6547650aa692dd98352888328",
            ["libggml-cpu-armv8.6_1.so"] = "56c54718e7af45f153590aacbce297f766b92e8edea0d0b082c0458d628affac",
            ["libggml-cpu-armv8.6_2.so"] = "a66c7e0c4e2c5416a4781044b6e67d8639461ce29127e9f5b06c583e4b112d1a",
            ["libggml-cpu-armv9.2_1.so"] = "179927383c9c9828d2cdb17684a090014367dcffed73f8c607407e076fe9089b",
            ["libggml-cpu-armv9.2_2.so"] = "d9586027654d4ea79a31d6752df77130dd9ab1a69cdc6cd3f49194616b901525",
            ["libggml.so"] = "0106d4f93be7f173fac78b5771048c1d6199b55adff535bd12b33b00f673ea3b",
            ["libggml.so.0"] = "0106d4f93be7f173fac78b5771048c1d6199b55adff535bd12b33b00f673ea3b",
            ["libggml.so.0.23.0"] = "0106d4f93be7f173fac78b5771048c1d6199b55adff535bd12b33b00f673ea3b",
            ["libwhisper.so"] = "2a0243e5dd1c7abd1393a0d5c42a44a55f5e5f3771f2530c06116641c2ca5528",
            ["libwhisper.so.1"] = "2a0243e5dd1c7abd1393a0d5c42a44a55f5e5f3771f2530c06116641c2ca5528",
            ["libwhisper.so.1.9.4"] = "2a0243e5dd1c7abd1393a0d5c42a44a55f5e5f3771f2530c06116641c2ca5528",
            ["whisper-cli"] = "23b5a65fb74a6d51b7fab0d2fe875db50f3da7ebd8a658be060f4e66157715d6",
        }),
        new("whisper-cli-linux-x64.zip", "95c6a5ffad17b99c2469680c2249e8a44e09c8b73d375404c13c9036dbe8d5d7", 9826049, new Dictionary<string, string>
        {
            ["LICENSE-whisper.cpp.txt"] = "94f29bbed6a22c35b992c5c6ebf0e7c92f13b836b90f36f461c9cf2f0f1d010d",
            ["libggml-base.so"] = "778f577d1437bf7a28e06584134acfd64e8a7eed73fabe8dac5cbd71c9ba8cc5",
            ["libggml-base.so.0"] = "778f577d1437bf7a28e06584134acfd64e8a7eed73fabe8dac5cbd71c9ba8cc5",
            ["libggml-base.so.0.23.0"] = "778f577d1437bf7a28e06584134acfd64e8a7eed73fabe8dac5cbd71c9ba8cc5",
            ["libggml-cpu-alderlake.so"] = "cb45474e27ccf92b1497bd720468429b9432588f2980624ffe8a15e8b1c6684d",
            ["libggml-cpu-cannonlake.so"] = "53d0b1846f98ef6dd8ce6b2b3ce26fe26923911e42fe89ac12545cfd454268e4",
            ["libggml-cpu-cascadelake.so"] = "d980af880944756d2b2defb393efa3109a42fbec782a10ded5390dd3e4c3ecc2",
            ["libggml-cpu-cooperlake.so"] = "34c66259eca8a3c7cbb8df6c8b44d679aff7f34598e33a8a4bba13399e65f707",
            ["libggml-cpu-haswell.so"] = "e5ecef88a4f39598446f119a37ecc2704bdfda3958a78859f58e6e11809e1f2d",
            ["libggml-cpu-icelake.so"] = "766ac5b8c3bc6a74ca4b4cd6281c3c351aa86484f6055afa072b4c6068164783",
            ["libggml-cpu-ivybridge.so"] = "7f0b6a7d63d8193748f3b25c4d24f5c182d4c420e5dd7bdd9747d188e965024a",
            ["libggml-cpu-piledriver.so"] = "def3000fcc6412f26626047e00bb98011133d5712218f735dd557a3295307e40",
            ["libggml-cpu-sandybridge.so"] = "be1873910101cab6c448204363844cb10d790c14fff1cb0089b7f962921e3a34",
            ["libggml-cpu-sapphirerapids.so"] = "e572f95bdab08a8d5206e6db0d61b699d45f1a0d8e29a9fa27807eaaf6563453",
            ["libggml-cpu-skylakex.so"] = "240e638a5c1ad3d52843199c344d03716562af12596be06b5d1b08302965a48b",
            ["libggml-cpu-sse42.so"] = "53a18d20af66ff1dfad832c6e9f737b2a7226a127c50f5c06345aa54eb60e91a",
            ["libggml-cpu-x64.so"] = "9b8c6da5d894832070c2d3ecc8e0b9baa4a0a75847707abd8a18832f035ae7f8",
            ["libggml-cpu-zen4.so"] = "7bd9dd5daec2ff6848c6bf2a7b23aa4d16d2197cca9f6221f0a206eb3fd49291",
            ["libggml.so"] = "4023c9dd1e2a3841f75fba6d4d01f0be1975fa4da4e5a05589d11020015e0e55",
            ["libggml.so.0"] = "4023c9dd1e2a3841f75fba6d4d01f0be1975fa4da4e5a05589d11020015e0e55",
            ["libggml.so.0.23.0"] = "4023c9dd1e2a3841f75fba6d4d01f0be1975fa4da4e5a05589d11020015e0e55",
            ["libwhisper.so"] = "5ff813932a4b65a36425a10b3fa77e81c6c32b73667ed411391ef7ad623d1543",
            ["libwhisper.so.1"] = "5ff813932a4b65a36425a10b3fa77e81c6c32b73667ed411391ef7ad623d1543",
            ["libwhisper.so.1.9.4"] = "5ff813932a4b65a36425a10b3fa77e81c6c32b73667ed411391ef7ad623d1543",
            ["whisper-cli"] = "5673bb88e9171c43564a8cd73b49bc65882707c08c0926840408d6b3866ec780",
        }),
        new("whisper-cli-macos-arm64.zip", "40d69d0858723878be6fdcdc3a979981d1e193c54fa91ab7a108d0f1304b5d50", 1085489, new Dictionary<string, string>
        {
            ["LICENSE-whisper.cpp.txt"] = "94f29bbed6a22c35b992c5c6ebf0e7c92f13b836b90f36f461c9cf2f0f1d010d",
            ["whisper-cli"] = "d11009c6176f4c9654a5a543885ff3bb7b9733a094ee559092817f18295b4c82",
        }),
        new("whisper-cli-macos-x64.zip", "19f03b01b8c2070c7596057c3701a6cb4cba54278a01c05abcae1764783cd6a4", 1280910, new Dictionary<string, string>
        {
            ["LICENSE-whisper.cpp.txt"] = "94f29bbed6a22c35b992c5c6ebf0e7c92f13b836b90f36f461c9cf2f0f1d010d",
            ["whisper-cli"] = "07f39e8971c885f8a04c24f1199d0248bc5206c57166a684c54a0a9c67ec0f7e",
        }),
        new("whisper-cli-windows-x64.zip", "29d5ff95c2b082f7515f3e69f5542a08513dc2bba6fb6e87bcff0e5c19219429", 3596133, new Dictionary<string, string>
        {
            ["LICENSE-whisper.cpp.txt"] = "bcd8ec749126d45cb06737d0690295d73df4b6e7e194205bcf91190368f27285",
            ["ggml-base.dll"] = "471e56c5ab80d920e681387c1c5d42d65599148168afb29528f2916c734b6455",
            ["ggml-cpu-alderlake.dll"] = "2e419e74f298b0ea69433963ff9e9c86db353b72c8ce3dd9e3f4a3eafeaa4e88",
            ["ggml-cpu-cannonlake.dll"] = "357f2edcce67c6815413c057889021857b549c582a4e384493bad2564c31272d",
            ["ggml-cpu-cascadelake.dll"] = "f1a3cba383b3d3154e97edd642310d6a37499bfb716193d168f9358383b290eb",
            ["ggml-cpu-haswell.dll"] = "685eea42e8e00215c2112d3aa4c0c76a9a04a37d217b55b2b12da800c14a6795",
            ["ggml-cpu-icelake.dll"] = "7b9706bdf3401138a0718bc1c4fc09677612d08b80a844929d5a441f1d490f7b",
            ["ggml-cpu-sandybridge.dll"] = "48db8524b6789036f79ad6d18a2840cbd32bf8a6b83e6641c01a00d7ef8d4650",
            ["ggml-cpu-skylakex.dll"] = "041f19b76981702429c440df5688047612c02521f45b3dd128a69163c59cf49d",
            ["ggml-cpu-sse42.dll"] = "71c49a8fd627df4609bed5807427926f9c927d851a5b19bf90e67d3c8932e980",
            ["ggml-cpu-x64.dll"] = "9398338dc13d1b4fa678624db9626c524de470a2b47f654b4b1bceededc6e86f",
            ["ggml.dll"] = "a746970290db661063e93e49b0e90c3e57adce4dabc6af9eaccf22fe83b302e0",
            ["whisper-cli.exe"] = "1f1ed1d9a3f0cafedb825a57c8dc7ffb51d8a4202c13b5a946ca2acde49fbacf",
            ["whisper.dll"] = "d203d53af3ca78f14bfb87227f36314efac924948b2a10d8cd2cadfcee369d87",
        }),
    ];
}
