// <auto-generated>
// Written by tools/builtin_checksums.py from the whisper-v1.9.4-2 release. Don't edit by hand.
// </auto-generated>

using System.Collections.Generic;

namespace Jellyfin.Plugin.Subtitles.SpeechToText.BuiltIn;

internal static partial class BuiltInRelease
{
    internal const string Tag = "whisper-v1.9.4-2";

    private static IReadOnlyList<BuiltInDownload> Downloads { get; } =
    [
        new("ggml-base-q8_0.bin", "c577b9a86e7e048a0b7eada054f4dd79a56bbfa911fbdacf900ac5b567cbb7d9", 81768585, null),
        new("ggml-small-q5_1.bin", "ae85e4a935d7a567bd102fe55afc16bb595bdb618e11b2fc7591bc08120411bb", 190085487, null),
        new("whisper-cli-linux-arm64.zip", "ace93223d2ee8e9b50f5479ec7d2c75eef0fca6b4a4c58fa9839472b87997bad", 4203404, new Dictionary<string, string>
        {
            ["LICENSE-whisper.cpp.txt"] = "94f29bbed6a22c35b992c5c6ebf0e7c92f13b836b90f36f461c9cf2f0f1d010d",
            ["libggml-base.so.0"] = "2221720b967d332065623626917bcce295b469be509749b0caca949dacff4a04",
            ["libggml-cpu-armv8.0_1.so"] = "e694a8008fd02308216baca7bf3e29bff4f5322674e5f6e7a107fac93773c92d",
            ["libggml-cpu-armv8.2_1.so"] = "1b2ce5a9351d2c843a91f5da022cb029d2303659490b66a8407b100dbb1ce5ea",
            ["libggml-cpu-armv8.2_2.so"] = "1e297f61a26e33d50239772fee1415e1a88e4e2b77bef70dfcc12f54d6e8f162",
            ["libggml-cpu-armv8.2_3.so"] = "8c22276b200844f43e8bf8180d6a83c4141911b9041ef81250eddbcf9e6d97d9",
            ["libggml-cpu-armv8.6_1.so"] = "93b9a0a732cb584ca5b0738cf224b2b8df8af1e238d6ec4bc534ad577bd5b492",
            ["libggml-cpu-armv8.6_2.so"] = "18e8980a7f01babbb384705d047d32ab525546a019a4461d40fa67d67ea26c4b",
            ["libggml-cpu-armv9.2_1.so"] = "f95528b79b4623a0f8b1dfdd6682eb5025b661158a2db9fa5f83533a3bdf3cbe",
            ["libggml-cpu-armv9.2_2.so"] = "34ce2128a38925ea8073e45c27e92e1da656516c5b3304b33499a38e7e162df2",
            ["libggml.so.0"] = "e3525210ba55772c135da74ee6cda3f0d11aeac805d193e74b4210be491cf0f1",
            ["libwhisper.so.1"] = "f897e28f2d44d0b94e8e260d8bb38ec67cbc1cd1626ba74fcb41e4ceec0de2c7",
            ["whisper-cli"] = "adcf6e6e502cbc9ff10fc9fa2c9e188d0f137cec09b58668224ae20d40b7d4a5",
        }),
        new("whisper-cli-linux-x64.zip", "ed08523288a3086e1fd0538e73775a65e0f9829934e45d17044e2dde81cb0a90", 6909787, new Dictionary<string, string>
        {
            ["LICENSE-whisper.cpp.txt"] = "94f29bbed6a22c35b992c5c6ebf0e7c92f13b836b90f36f461c9cf2f0f1d010d",
            ["libggml-base.so.0"] = "3bfd33848019b8d676496e3c8bd554b1c386895ac147c235324cb2d638a84a3c",
            ["libggml-cpu-alderlake.so"] = "74ddfd7d5abc328a89740924b1a95c5900d5eb9a0e0a21f9537618ffad850bbb",
            ["libggml-cpu-cannonlake.so"] = "0d671d6ff3774900c7823cbf20382dd1fe21f4312e290b22d2a374d97d65a94d",
            ["libggml-cpu-cascadelake.so"] = "c23961b494798fc81273d98908120857b90f9f16fecc23be1367322b8fec725b",
            ["libggml-cpu-cooperlake.so"] = "4cf67ff64baa5417e6d215047b52a0f6e69bb7668a082f62144c8d870e05bd76",
            ["libggml-cpu-haswell.so"] = "1c50927450c956b276ea83727a4f0a61eaa91f5299380efe4fed5f6e31cda3e9",
            ["libggml-cpu-icelake.so"] = "4a55d5b1c3959367d9203a9dfbac418031dd088fefa86259739fb28b5cf38e60",
            ["libggml-cpu-ivybridge.so"] = "8168887a9fe08b75ebab483a034b9c45fde562276cf94d249ee57d8ce21144ae",
            ["libggml-cpu-piledriver.so"] = "4d59844c387c7f797ca99bfba3bec2b402dfd4c4c7cfb37c865f07a35731a327",
            ["libggml-cpu-sandybridge.so"] = "5b8d0dd8afb4134bdc6bfa29191d62bbe5ba7873af286ef7c8004b2d1afd6b38",
            ["libggml-cpu-sapphirerapids.so"] = "bfcb152ff0f345f281488df05929c3b5ac76b3e2c0672a1717600d2b92f75de5",
            ["libggml-cpu-skylakex.so"] = "3b84798f0bfb344b73b446166497396e09c09ab2d8c7ce1d3e6cb939ad7319d7",
            ["libggml-cpu-sse42.so"] = "1823cf4085afae3552d494100c3c98a5a611151415ff359fad0eb3c9f4662a9e",
            ["libggml-cpu-x64.so"] = "a04fd4d85bd52c1d905017db1f8e3597def3a803b6618736a7c345e775a1d663",
            ["libggml-cpu-zen4.so"] = "62229af21c21a218732ca9338070b31c0586cbfc94903102606bcd34c78f5fc6",
            ["libggml.so.0"] = "20b3bca4e57f79922d910b6bdfaa3c767a4742aaef494c3b49ec67b6654b9769",
            ["libwhisper.so.1"] = "d9f6ded3e5ec892c07ee40c4f4d2cff93b92e82aac56c22994def22b69ef0187",
            ["whisper-cli"] = "7fe99192fbf3e2488475cecbcd964af643fc088735fb3be6e9d7d6d0ff91ed71",
        }),
        new("whisper-cli-macos-arm64.zip", "2e5cdcd18f993e4c45a99e3409168c285e4dff4871920f5d4de097d1a8de60cc", 1081005, new Dictionary<string, string>
        {
            ["LICENSE-whisper.cpp.txt"] = "94f29bbed6a22c35b992c5c6ebf0e7c92f13b836b90f36f461c9cf2f0f1d010d",
            ["whisper-cli"] = "d11009c6176f4c9654a5a543885ff3bb7b9733a094ee559092817f18295b4c82",
        }),
        new("whisper-cli-macos-x64.zip", "53260d6e3e3820258e056bae3237bcb0bdf2290fa10b08430fe121183aec7981", 1274501, new Dictionary<string, string>
        {
            ["LICENSE-whisper.cpp.txt"] = "94f29bbed6a22c35b992c5c6ebf0e7c92f13b836b90f36f461c9cf2f0f1d010d",
            ["whisper-cli"] = "07f39e8971c885f8a04c24f1199d0248bc5206c57166a684c54a0a9c67ec0f7e",
        }),
        new("whisper-cli-windows-x64.zip", "31d54d7060bcd710fce1556aeed7f2650c94c7f5600c8483567cf95c1420ef03", 3570675, new Dictionary<string, string>
        {
            ["LICENSE-whisper.cpp.txt"] = "bcd8ec749126d45cb06737d0690295d73df4b6e7e194205bcf91190368f27285",
            ["ggml-base.dll"] = "77cf8270ff5b79769bdc05fca7634149ec3d30f223d95128b0c4c2f5c90372d9",
            ["ggml-cpu-alderlake.dll"] = "4b7602e82ec09e3aff8133143512f676157d7b0818669e783bfd90bdbf648de9",
            ["ggml-cpu-cannonlake.dll"] = "f013ad951b55659031511bce2f6a74c94af555c013da4c97c7c59be3f0de9ec7",
            ["ggml-cpu-cascadelake.dll"] = "22d97b985514e042a9ff76bcb5ceb2ad24a41ca53a467f2f9c7662463be2b94b",
            ["ggml-cpu-haswell.dll"] = "3b1d76bd84e61cf62ddb57617404ae103212b86cbe4ed91742d31e5586afc41a",
            ["ggml-cpu-icelake.dll"] = "6c5c24b9f74f42c8c1a7b4868f7bd7279e8ef03ea5007fc81a6fec6cb09e7354",
            ["ggml-cpu-sandybridge.dll"] = "1ea54be1b1b4a9f435e81775ee53b462ddaa2dbc50e7b76fe34a4e23888d5ac2",
            ["ggml-cpu-skylakex.dll"] = "27ef02848c65a1403633cdf433fc4beec9efa05b8c98388df1673e2774a3209a",
            ["ggml-cpu-sse42.dll"] = "77de327645d025cd69d7edee0ad44d3ce7aad97815e6725ed3081b4384c52fbd",
            ["ggml-cpu-x64.dll"] = "4e4c0b9f6e0086edd88cc6c11379b840cf87668224cdfd5858c7724b95bdad0c",
            ["ggml.dll"] = "8be721ed3be6a29944c22361ed0df14da47d35e41b42766a8e638effba7d849f",
            ["whisper-cli.exe"] = "07af2469e184252c7704df6cc2e02583f8b69949451f60266365d2676a7c385e",
            ["whisper.dll"] = "246ccb86f5c9b7c59449c21bb7800e05b302d3dc941398a6004e32ca66f1eae0",
        }),
    ];
}
