#!/usr/bin/env python3
"""Writes BuiltInRelease.Checksums.cs from a published whisper-v* release's whisper-files.json.

The built-in speech-to-text only runs files whose SHA-256 is compiled into the plugin, so a new whisper.cpp build or
model is adopted by running this against its release and committing the result:

    tools/builtin_checksums.py whisper-v1.9.4-1

It downloads whisper-files.json and SHA256SUMS from that release, checks one against the other, and writes the C# file.
"""

import hashlib
import json
import pathlib
import sys
import urllib.request

REPO = "chrisgrulau/jellyfin-subtitles"
OUT = pathlib.Path(__file__).resolve().parent.parent / "src/Jellyfin.Plugin.Subtitles/SpeechToText/BuiltIn/BuiltInRelease.Checksums.cs"


def fetch(tag, name):
    url = f"https://github.com/{REPO}/releases/download/{tag}/{name}"
    with urllib.request.urlopen(urllib.request.Request(url, headers={"User-Agent": "builtin-checksums"}), timeout=60) as r:
        return r.read()


def cs(s):
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


def main():
    if len(sys.argv) != 2 or not sys.argv[1].startswith("whisper-v"):
        sys.exit("usage: tools/builtin_checksums.py whisper-v<version>-<n>")
    tag = sys.argv[1]
    files_json = fetch(tag, "whisper-files.json")
    sums = dict(reversed(line.split()) for line in fetch(tag, "SHA256SUMS").decode().splitlines() if line.strip())
    if sums.get("whisper-files.json") != hashlib.sha256(files_json).hexdigest():
        sys.exit("whisper-files.json doesn't match SHA256SUMS")
    data = json.loads(files_json)
    if data["tag"] != tag:
        sys.exit(f"whisper-files.json is for {data['tag']}, not {tag}")

    lines = [
        "// <auto-generated>",
        f"// Written by tools/builtin_checksums.py from the {tag} release. Don't edit by hand.",
        "// </auto-generated>",
        "",
        "using System.Collections.Generic;",
        "",
        "namespace Jellyfin.Plugin.Subtitles.SpeechToText.BuiltIn;",
        "",
        "internal static partial class BuiltInRelease",
        "{",
        f"    internal const string Tag = {cs(tag)};",
        "",
        "    private static IReadOnlyList<BuiltInDownload> Downloads { get; } =",
        "    [",
    ]
    for name, entry in sorted(data["downloads"].items()):
        if sums.get(name) != entry["sha256"]:
            sys.exit(f"{name}: whisper-files.json and SHA256SUMS disagree")
        files = entry.get("files")
        if files is None:
            lines.append(f"        new({cs(name)}, {cs(entry['sha256'])}, {entry['bytes']}, null),")
        else:
            lines.append(f"        new({cs(name)}, {cs(entry['sha256'])}, {entry['bytes']}, new Dictionary<string, string>")
            lines.append("        {")
            for f, h in sorted(files.items()):
                lines.append(f"            [{cs(f)}] = {cs(h)},")
            lines.append("        }),")
    lines += ["    ];", "}", ""]
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {OUT.relative_to(OUT.parents[3])} ({len(data['downloads'])} downloads)")


if __name__ == "__main__":
    main()
